### PR TITLE
Fix scanimage source mode to fit hp devices

### PR DESCRIPTION
**Pull request by matbgn**
scanimage 1.0.27

### CODE REVIEW

**Comment by wuan** [comment]
Hm, that does not work here, e. g. using Ubuntu 20.04:
```
$ scanimage -b --source Duplex
Output format is not set, using pnm as a default.
scanimage: setting of option --source failed (Invalid argument)
```
with version
```
$ scanimage --version
scanimage (sane-backends) 1.0.29; backend version 1.0.29
```

**Comment by wuan** [comment]
Maybe it depends on the scanner device. Does the script fail for your device?

**Comment by matbgn** [comment]
Yeah you're right! I will figure out how to address and complete my PR

**Comment by wuan** [comment]
@matbgn after merging the code I added support to have the device reference as an argument. Unfortunately the ADF configuration needed to be reverted. I'm not sure if these areguments are device specific or depend on the version of `scanimage`. To make that work, we could add a static configuration file later.

**Pull request merged**
